# version: '3.8'

services:
    mariadb:
        build: ./requirements/mariadb/
        expose:
            - "3306"
        networks:
            - intra
        env_file:
          - ../srcs/.env
    # nginx:
    #     build: ./requirements/nginx/
    #     restart: always
    #     ports:
    #         - "443:443"
    #     volumes:
    #         - data:/var/www/html
    #     networks:
    #         - intra
    #     depends_on:
    #         - mariadb
    # wordpress:
    #     build: ./requirements/wordpress/
    #     restart: always
    #     volumes:
    #         - data:/var/www/html
    #     expose: 
    #         - "9000"
    #     networks:
    #         - intra
    #     depends_on:
    #         - nginx

networks:
    intra:
        driver: bridge

volumes:
    data: {}