# version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        expose:
            - "3306"
        networks:
            - seonggoc
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
          - .env
    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - seonggoc
        depends_on:
            - wordpress
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        volumes:
            - wordpress:/var/www/html
        expose: 
            - "9000"
        networks:
            - seonggoc
        depends_on:
            - mariadb

networks:
    seonggoc:
      driver: bridge

volumes:
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        device: /home/seonggoc/data/mariadb
        o: bind

    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        device: /home/seonggoc/data/wordpress
        o: bind