# version: '3'

volumes:
    data: {}
services:
    mariadb:
        image: debian:bullseye
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
        env_file:
          - ../srcs/.env
    nginx:
        image: debian:bullseye
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true
    wordpress:
        image: debian:bullseye
        restart: always
        volumes:
            - data:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
